# Generated by Django 4.2.7 on 2023-11-18 20:54

import Main_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(default='default.png', null=True, upload_to=Main_app.models.unique_image_name)),
                ('owner', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('isuzu', ' Isuzu'), ('toyota', 'Toyota'), ('mercedes-benz', 'Mercedes -Benz'), ('tata tipper', 'Tata Tipper')], max_length=100)),
                ('type', models.CharField(choices=[('lorry', 'Lorry'), ('truck', 'Truck'), ('pickup', 'Pickup')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('for_hire_or_sell', models.CharField(choices=[('hire', 'Hire'), ('sell', 'Sell')], max_length=20)),
                ('image', models.ImageField(upload_to=Main_app.models.unique_vehicle_image_name)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Main_app.profile')),
            ],
        ),
    ]
