# Generated by Django 4.2.7 on 2023-11-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(choices=[('isuzu', ' Isuzu'), ('toyota', 'Toyota'), ('mercedes-benz', 'Mercedes -Benz'), ('tata tipper', 'Tata Tipper'), ('mitsubishi', 'Mitsubishi'), ('others', 'Others')], max_length=100),
        ),
    ]
