# Generated by Django 4.2.7 on 2023-11-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0003_transaction_alter_vehicle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Main_app.vehicle'),
            preserve_default=False,
        ),
    ]
