# Generated by Django 4.2.7 on 2023-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0004_transaction_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
