# Generated by Django 4.2.7 on 2023-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
