# Generated by Django 4.2.7 on 2023-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0007_vehicle_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='Cargo', max_length=100),
            preserve_default=False,
        ),
    ]
